### ISSUE TITLE
koa-jwt SyntaxError: Unexpected token function 

### ISSUE THREAD

**Issue by xnathanh** [koajs/jwt#105]
error when use node --debug bin/run to debug on VSC
try node version 7.0-7.9 all failed

`
Debugging with legacy protocol because a runtime executable is set.
npm run-script start 
> pro@0.1.0 start /Users/xxx/Desktop/pro
> nodemon --debug bin/run
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node --debug bin/run`
Debugger listening on 127.0.0.1:5858
/Users/xxx/Desktop/pro/node_modules/koa-jwt/lib/index.js:17
    const middleware = async function jwt(ctx, next) {
                                                 ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/xxx/Desktop/pro/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/nathanmb/Desktop/luim/app.js:16:13)
    at Module._compile (module.js:571:32)
    at loader (/Users/xxx/Desktop/pro/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/xxx/Desktop/pro/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
[nodemon] app crashed - waiting for file changes before starting...
`

**Comment by sdd** [comment]
This happens when you are running on a node version that does not support async / await. Try using `koa-jwt` version 2.
